<?php
/**
 * Master brand directory - generated from the Headshop Brands Master List.
 * 366 active brands (ranked) + 14 recently-joined brands (rank 7).
 * Value=0 brands excluded. Double-quoted strings for apostrophe safety.
 *
 * @package SmokeDropNoir
 */

function sdn_brand_directory() {
    return array(
        array( 'name' => "Puffco", 'slug' => "puffco", 'initials' => "PU", 'value' => 10, 'logo' => "2023/07/puffco-300x162.png" ),
        array( 'name' => "RAW", 'slug' => "raw", 'initials' => "RA", 'value' => 10, 'logo' => "2023/07/raw-300x162.png" ),
        array( 'name' => "Storz & Bickel", 'slug' => "storz-and-bickel", 'initials' => "SB", 'value' => 10, 'images' => array(
            'logo' => 'Storz-Bickel.png',
            'img1' => 'Storz-Bickel-600x600.jpg',
            'img2' => 'Snapinst.app_470679373_1040965324466559_7178810035500507420_n_1080.jpg',
        ) ),
        array( 'name' => "Stündenglass", 'slug' => "stundenglass", 'initials' => "ST", 'value' => 10 ),
        array( 'name' => "Vessel", 'slug' => "vessel", 'initials' => "VE", 'value' => 10, 'logo' => "2024/08/vessel0-300x162.jpg" ),
        array( 'name' => "Arizer", 'slug' => "arizer", 'initials' => "AR", 'value' => 9 ),
        array( 'name' => "Blazy Susan", 'slug' => "blazy-susan", 'initials' => "BS", 'value' => 9 ),
        array( 'name' => "Blunt Wrap", 'slug' => "blunt-wrap", 'initials' => "BW", 'value' => 9 ),
        array( 'name' => "CCell", 'slug' => "ccell", 'initials' => "CC", 'value' => 9, 'images' => array(
            'logo' => 'CCell.png',
            'img1' => 'Snapinst.app_441764211_1614126682758283_6118410090591023648_n_1024.jpg',
            'img2' => 'CCell1.jpg',
            'img3' => 'Snapinst.app_458413760_18335374555134934_5419868033705028228_n_1024.webp',
        ) ),
        array( 'name' => "Cheech Glass", 'slug' => "cheech-glass", 'initials' => "CG", 'value' => 9 ),
        array( 'name' => "DaVinci", 'slug' => "davinci", 'initials' => "DA", 'value' => 9 ),
        array( 'name' => "Dart", 'slug' => "dart", 'initials' => "DA", 'value' => 9 ),
        array( 'name' => "Dime Bags", 'slug' => "dime-bags", 'initials' => "DB", 'value' => 9 ),
        array( 'name' => "Dr. Dabber", 'slug' => "dr-dabber", 'initials' => "DD", 'value' => 9, 'logo' => "2023/07/drdabber-300x162.png" ),
        array( 'name' => "DynaVap", 'slug' => "dynavap", 'initials' => "DY", 'value' => 9 ),
        array( 'name' => "Elements Rolling Papers", 'slug' => "elements-rolling-papers", 'initials' => "ER", 'value' => 9 ),
        array( 'name' => "Empire Glass", 'slug' => "empire-glass", 'initials' => "EG", 'value' => 9 ),
        array( 'name' => "Eyce", 'slug' => "eyce", 'initials' => "EY", 'value' => 9, 'logo' => "2023/07/eyce-300x162.png" ),
        array( 'name' => "Freeze Pipe", 'slug' => "freeze-pipe", 'initials' => "FP", 'value' => 9 ),
        array( 'name' => "Fujima", 'slug' => "fujima", 'initials' => "FU", 'value' => 9 ),
        array( 'name' => "G Pen", 'slug' => "g-pen", 'initials' => "GP", 'value' => 9 ),
        array( 'name' => "GRAV", 'slug' => "grav", 'initials' => "GR", 'value' => 9, 'logo' => "2023/07/gravb-300x162.png" ),
        array( 'name' => "Honeybee Herb", 'slug' => "honeybee-herb", 'initials' => "HH", 'value' => 9 ),
        array( 'name' => "Human Grade", 'slug' => "human-grade", 'initials' => "HG", 'value' => 9 ),
        array( 'name' => "Invincibowl", 'slug' => "invincibowl", 'initials' => "IN", 'value' => 9 ),
        array( 'name' => "King Palm", 'slug' => "king-palm", 'initials' => "KP", 'value' => 9 ),
        array( 'name' => "Lookah", 'slug' => "lookah", 'initials' => "LO", 'value' => 9 ),
        array( 'name' => "Lord of the Rings", 'slug' => "lord-of-the-rings", 'initials' => "LO", 'value' => 9 ),
        array( 'name' => "MJ Arsenal", 'slug' => "mj-arsenal", 'initials' => "MA", 'value' => 9 ),
        array( 'name' => "Modern Herb Co", 'slug' => "modern-herb-co", 'initials' => "MH", 'value' => 9 ),
        array( 'name' => "NUUD", 'slug' => "nuud", 'initials' => "NU", 'value' => 9 ),
        array( 'name' => "NWTN", 'slug' => "nwtn", 'initials' => "NW", 'value' => 9 ),
        array( 'name' => "Neometrx", 'slug' => "neometrx", 'initials' => "NE", 'value' => 9 ),
        array( 'name' => "OCB Rolling Papers", 'slug' => "ocb-rolling-papers", 'initials' => "OR", 'value' => 9 ),
        array( 'name' => "Ongrok", 'slug' => "ongrok", 'initials' => "ON", 'value' => 9 ),
        array( 'name' => "PAX", 'slug' => "pax", 'initials' => "PA", 'value' => 9, 'logo' => "2023/07/pax-1-300x162.png" ),
        array( 'name' => "Pulsar", 'slug' => "pulsar", 'initials' => "PU", 'value' => 9, 'logo' => "2023/07/pulsar-300x162.png" ),
        array( 'name' => "RYOT", 'slug' => "ryot", 'initials' => "RY", 'value' => 9 ),
        array( 'name' => "Revelry Hemp", 'slug' => "revelry-hemp", 'initials' => "RH", 'value' => 9 ),
        array( 'name' => "Revelry Supply", 'slug' => "revelry-supply", 'initials' => "RS", 'value' => 9 ),
        array( 'name' => "Yocan", 'slug' => "yocan", 'initials' => "YO", 'value' => 9 ),
        array( 'name' => "Zenco", 'slug' => "zenco", 'initials' => "ZE", 'value' => 9 ),
        array( 'name' => "Zippo Lighters", 'slug' => "zippo-lighters", 'initials' => "ZL", 'value' => 9 ),
        array( 'name' => "Ash Rolling Papers", 'slug' => "ash-rolling-papers", 'initials' => "AR", 'value' => 8 ),
        array( 'name' => "BOMB", 'slug' => "bomb", 'initials' => "BO", 'value' => 8 ),
        array( 'name' => "Bear Quartz", 'slug' => "bear-quartz", 'initials' => "BQ", 'value' => 8 ),
        array( 'name' => "Boundless", 'slug' => "boundless", 'initials' => "BO", 'value' => 8 ),
        array( 'name' => "Cali Crusher", 'slug' => "cali-crusher", 'initials' => "CC", 'value' => 8 ),
        array( 'name' => "Cheech and Chong Glass", 'slug' => "cheech-and-chong-glass", 'initials' => "CA", 'value' => 8 ),
        array( 'name' => "Chill", 'slug' => "chill", 'initials' => "CH", 'value' => 8 ),
        array( 'name' => "Cloudious", 'slug' => "cloudious", 'initials' => "CL", 'value' => 8 ),
        array( 'name' => "Cookies", 'slug' => "cookies", 'initials' => "CO", 'value' => 8, 'logo' => "2023/07/brand-cookies-2-300x162.png" ),
        array( 'name' => "Dabtized", 'slug' => "dabtized", 'initials' => "DA", 'value' => 8 ),
        array( 'name' => "Daze Glass", 'slug' => "daze-glass", 'initials' => "DG", 'value' => 8 ),
        array( 'name' => "ELFTHC", 'slug' => "elfthc", 'initials' => "EL", 'value' => 8 ),
        array( 'name' => "Flower Mill", 'slug' => "flower-mill", 'initials' => "FM", 'value' => 8 ),
        array( 'name' => "Focus V", 'slug' => "focus-v", 'initials' => "FV", 'value' => 8 ),
        array( 'name' => "G-Rollz", 'slug' => "g-rollz", 'initials' => "GR", 'value' => 8 ),
        array( 'name' => "Gold Naturals", 'slug' => "gold-naturals", 'initials' => "GN", 'value' => 8 ),
        array( 'name' => "Grateful Dead", 'slug' => "grateful-dead", 'initials' => "GD", 'value' => 8 ),
        array( 'name' => "Hamilton Devices", 'slug' => "hamilton-devices", 'initials' => "HD", 'value' => 8 ),
        array( 'name' => "Hitoki", 'slug' => "hitoki", 'initials' => "HI", 'value' => 8 ),
        array( 'name' => "HoneyStick", 'slug' => "honeystick", 'initials' => "HO", 'value' => 8 ),
        array( 'name' => "Houseplant", 'slug' => "houseplant", 'initials' => "HO", 'value' => 8 ),
        array( 'name' => "Infyniti", 'slug' => "infyniti", 'initials' => "IN", 'value' => 8 ),
        array( 'name' => "Journey Pipe", 'slug' => "journey-pipe", 'initials' => "JP", 'value' => 8 ),
        array( 'name' => "Kannastor", 'slug' => "kannastor", 'initials' => "KA", 'value' => 8 ),
        array( 'name' => "Kill Your Culture", 'slug' => "kill-your-culture", 'initials' => "KY", 'value' => 8 ),
        array( 'name' => "Lemonnade", 'slug' => "lemonnade", 'initials' => "LE", 'value' => 8 ),
        array( 'name' => "My Bud Vase", 'slug' => "my-bud-vase", 'initials' => "MB", 'value' => 8 ),
        array( 'name' => "OOZE", 'slug' => "ooze", 'initials' => "OO", 'value' => 8 ),
        array( 'name' => "PieceMaker", 'slug' => "piecemaker", 'initials' => "PI", 'value' => 8 ),
        array( 'name' => "QCarbo", 'slug' => "qcarbo", 'initials' => "QC", 'value' => 8 ),
        array( 'name' => "Red Eye Tek", 'slug' => "red-eye-tek", 'initials' => "RE", 'value' => 8 ),
        array( 'name' => "SeshGear", 'slug' => "seshgear", 'initials' => "SE", 'value' => 8 ),
        array( 'name' => "Shine", 'slug' => "shine", 'initials' => "SH", 'value' => 8 ),
        array( 'name' => "Smoke Honest", 'slug' => "smoke-honest", 'initials' => "SH", 'value' => 8 ),
        array( 'name' => "Softglass", 'slug' => "softglass", 'initials' => "SO", 'value' => 8 ),
        array( 'name' => "Space King", 'slug' => "space-king", 'initials' => "SK", 'value' => 8 ),
        array( 'name' => "Special Blue", 'slug' => "special-blue", 'initials' => "SB", 'value' => 8 ),
        array( 'name' => "Stache", 'slug' => "stache", 'initials' => "ST", 'value' => 8 ),
        array( 'name' => "Stashlogix", 'slug' => "stashlogix", 'initials' => "ST", 'value' => 8 ),
        array( 'name' => "Swiss Vitalis", 'slug' => "swiss-vitalis", 'initials' => "SV", 'value' => 8 ),
        array( 'name' => "Toker Poker", 'slug' => "toker-poker", 'initials' => "TP", 'value' => 8 ),
        array( 'name' => "Truweigh", 'slug' => "truweigh", 'initials' => "TR", 'value' => 8 ),
        array( 'name' => "Tyson 2.0", 'slug' => "tyson-20", 'initials' => "T2", 'value' => 8 ),
        array( 'name' => "Vector", 'slug' => "vector", 'initials' => "VE", 'value' => 8 ),
        array( 'name' => "Vitae Glass", 'slug' => "vitae-glass", 'initials' => "VG", 'value' => 8 ),
        array( 'name' => "Wacky Bowlz", 'slug' => "wacky-bowlz", 'initials' => "WB", 'value' => 8 ),
        array( 'name' => "Waxmaid", 'slug' => "waxmaid", 'initials' => "WA", 'value' => 8, 'logo' => "2023/07/wax-maid-300x162.png" ),
        array( 'name' => "Xvape", 'slug' => "xvape", 'initials' => "XV", 'value' => 8 ),
        array( 'name' => "Zeus Arsenal", 'slug' => "zeus-arsenal", 'initials' => "ZA", 'value' => 8 ),
        array( 'name' => "ZigZag", 'slug' => "zigzag", 'initials' => "ZI", 'value' => 8 ),
        array( 'name' => "Beamer Candle", 'slug' => "beamer-candle", 'initials' => "BC", 'value' => 7 ),
        array( 'name' => "Bearded", 'slug' => "bearded", 'initials' => "BE", 'value' => 7 ),
        array( 'name' => "Benji Papers", 'slug' => "benji-papers", 'initials' => "BP", 'value' => 7 ),
        array( 'name' => "BlackCraft Extrax", 'slug' => "blackcraft-extrax", 'initials' => "BE", 'value' => 7 ),
        array( 'name' => "Blazer", 'slug' => "blazer", 'initials' => "BL", 'value' => 7 ),
        array( 'name' => "Boveda", 'slug' => "boveda", 'initials' => "BO", 'value' => 7 ),
        array( 'name' => "Brisco Brands", 'slug' => "brisco-brands", 'initials' => "BB", 'value' => 7 ),
        array( 'name' => "Canada Puffin", 'slug' => "canada-puffin", 'initials' => "CP", 'value' => 7 ),
        array( 'name' => "Cartisan", 'slug' => "cartisan", 'initials' => "CA", 'value' => 7 ),
        array( 'name' => "Cheef Relief", 'slug' => "cheef-relief", 'initials' => "CR", 'value' => 7 ),
        array( 'name' => "Connect", 'slug' => "connect", 'initials' => "CO", 'value' => 7 ),
        array( 'name' => "Delta Munchies", 'slug' => "delta-munchies", 'initials' => "DM", 'value' => 7 ),
        array( 'name' => "Diamond Glass", 'slug' => "diamond-glass", 'initials' => "DG", 'value' => 7 ),
        array( 'name' => "FONZ", 'slug' => "fonz", 'initials' => "FO", 'value' => 7 ),
        array( 'name' => "Flux", 'slug' => "flux", 'initials' => "FL", 'value' => 7 ),
        array( 'name' => "Geekvape", 'slug' => "geekvape", 'initials' => "GE", 'value' => 7 ),
        array( 'name' => "Glob Mops", 'slug' => "glob-mops", 'initials' => "GM", 'value' => 7 ),
        array( 'name' => "Glow Guard Bong Base Bumper", 'slug' => "glow-guard-bong-base-bumper", 'initials' => "GG", 'value' => 7 ),
        array( 'name' => "Habit", 'slug' => "habit", 'initials' => "HA", 'value' => 7 ),
        array( 'name' => "Hemper", 'slug' => "hemper", 'initials' => "HE", 'value' => 7, 'logo' => "2023/07/hemper-300x162.png" ),
        array( 'name' => "Her Highness", 'slug' => "her-highness", 'initials' => "HH", 'value' => 7 ),
        array( 'name' => "Herbal Clean", 'slug' => "herbal-clean", 'initials' => "HC", 'value' => 7 ),
        array( 'name' => "High Society", 'slug' => "high-society", 'initials' => "HS", 'value' => 7 ),
        array( 'name' => "High Times", 'slug' => "high-times", 'initials' => "HT", 'value' => 7 ),
        array( 'name' => "High Voltage", 'slug' => "high-voltage", 'initials' => "HV", 'value' => 7 ),
        array( 'name' => "Higher Standards", 'slug' => "higher-standards", 'initials' => "HS", 'value' => 7 ),
        array( 'name' => "Hillside Glass", 'slug' => "hillside-glass", 'initials' => "HG", 'value' => 7 ),
        array( 'name' => "Honey Labs", 'slug' => "honey-labs", 'initials' => "HL", 'value' => 7 ),
        array( 'name' => "Jiffy Geeb", 'slug' => "jiffy-geeb", 'initials' => "JG", 'value' => 7 ),
        array( 'name' => "Juicy Jays", 'slug' => "juicy-jays", 'initials' => "JJ", 'value' => 7 ),
        array( 'name' => "Klean Glass", 'slug' => "klean-glass", 'initials' => "KG", 'value' => 7 ),
        array( 'name' => "KushKards", 'slug' => "kushkards", 'initials' => "KU", 'value' => 7 ),
        array( 'name' => "LEVO", 'slug' => "levo", 'initials' => "LE", 'value' => 7 ),
        array( 'name' => "Magical Butter", 'slug' => "magical-butter", 'initials' => "MB", 'value' => 7 ),
        array( 'name' => "Marley Natural", 'slug' => "marley-natural", 'initials' => "MN", 'value' => 7, 'logo' => "2023/07/marley-300x162.png" ),
        array( 'name' => "Marley One", 'slug' => "marley-one", 'initials' => "MO", 'value' => 7 ),
        array( 'name' => "MasterKush", 'slug' => "masterkush", 'initials' => "MA", 'value' => 7 ),
        array( 'name' => "O.pen", 'slug' => "open", 'initials' => "OP", 'value' => 7, 'logo' => "2024/08/o.pen_-300x162.jpg" ),
        array( 'name' => "Original Nectar Collector", 'slug' => "original-nectar-collector", 'initials' => "ON", 'value' => 7 ),
        array( 'name' => "Penjamin", 'slug' => "penjamin", 'initials' => "PE", 'value' => 7 ),
        array( 'name' => "Phenom", 'slug' => "phenom", 'initials' => "PH", 'value' => 7 ),
        array( 'name' => "Philter", 'slug' => "philter", 'initials' => "PH", 'value' => 7 ),
        array( 'name' => "Phoenix Rising", 'slug' => "phoenix-rising", 'initials' => "PR", 'value' => 7 ),
        array( 'name' => "Playboy", 'slug' => "playboy", 'initials' => "PL", 'value' => 7 ),
        array( 'name' => "Power Hitter", 'slug' => "power-hitter", 'initials' => "PH", 'value' => 7 ),
        array( 'name' => "Purple Rose Supply", 'slug' => "purple-rose-supply", 'initials' => "PR", 'value' => 7 ),
        array( 'name' => "SharpStone", 'slug' => "sharpstone", 'initials' => "SH", 'value' => 7 ),
        array( 'name' => "Smokebuddy", 'slug' => "smokebuddy", 'initials' => "SM", 'value' => 7 ),
        array( 'name' => "Staze", 'slug' => "staze", 'initials' => "ST", 'value' => 7 ),
        array( 'name' => "Stinger", 'slug' => "stinger", 'initials' => "ST", 'value' => 7 ),
        array( 'name' => "Threadheads", 'slug' => "threadheads", 'initials' => "TH", 'value' => 7 ),
        array( 'name' => "Thug Life", 'slug' => "thug-life", 'initials' => "TL", 'value' => 7 ),
        array( 'name' => "Utest", 'slug' => "utest", 'initials' => "UT", 'value' => 7 ),
        array( 'name' => "Vibes", 'slug' => "vibes", 'initials' => "VI", 'value' => 7 ),
        array( 'name' => "WYLD", 'slug' => "wyld", 'initials' => "WY", 'value' => 7 ),
        array( 'name' => "aLeaf", 'slug' => "aleaf", 'initials' => "AL", 'value' => 7 ),
        array( 'name' => "cbdMD", 'slug' => "cbdmd", 'initials' => "CB", 'value' => 7 ),
        array( 'name' => "420 Science", 'slug' => "420-science", 'initials' => "4S", 'value' => 6 ),
        array( 'name' => "Alchemy Naturals", 'slug' => "alchemy-naturals", 'initials' => "AN", 'value' => 6, 'logo' => "2024/08/alchemy-naturals-300x162.jpg" ),
        array( 'name' => "BEED", 'slug' => "beed", 'initials' => "BE", 'value' => 6 ),
        array( 'name' => "Biird", 'slug' => "biird", 'initials' => "BI", 'value' => 6 ),
        array( 'name' => "Billionaire Hemp Wraps", 'slug' => "billionaire-hemp-wraps", 'initials' => "BH", 'value' => 6 ),
        array( 'name' => "Bluebus", 'slug' => "bluebus", 'initials' => "BL", 'value' => 6 ),
        array( 'name' => "Bob Marley Rolling Papers", 'slug' => "bob-marley-rolling-papers", 'initials' => "BM", 'value' => 6 ),
        array( 'name' => "CVault", 'slug' => "cvault", 'initials' => "CV", 'value' => 6 ),
        array( 'name' => "Carolina Cannabis Creations", 'slug' => "carolina-cannabis-creations", 'initials' => "CC", 'value' => 6 ),
        array( 'name' => "Coochy", 'slug' => "coochy", 'initials' => "CO", 'value' => 6 ),
        array( 'name' => "DabPadz", 'slug' => "dabpadz", 'initials' => "DA", 'value' => 6 ),
        array( 'name' => "East Coasters", 'slug' => "east-coasters", 'initials' => "EC", 'value' => 6 ),
        array( 'name' => "Elephant 9000", 'slug' => "elephant-9000", 'initials' => "E9", 'value' => 6 ),
        array( 'name' => "Everyday Canna Co", 'slug' => "everyday-canna-co", 'initials' => "EC", 'value' => 6 ),
        array( 'name' => "Formula 420", 'slug' => "formula-420", 'initials' => "F4", 'value' => 6 ),
        array( 'name' => "GEAR Premium", 'slug' => "gear-premium", 'initials' => "GP", 'value' => 6 ),
        array( 'name' => "Green Man", 'slug' => "green-man", 'initials' => "GM", 'value' => 6 ),
        array( 'name' => "Grunge Off", 'slug' => "grunge-off", 'initials' => "GO", 'value' => 6 ),
        array( 'name' => "Hempire", 'slug' => "hempire", 'initials' => "HE", 'value' => 6 ),
        array( 'name' => "Hempmetics", 'slug' => "hempmetics", 'initials' => "HE", 'value' => 6 ),
        array( 'name' => "HiXotic", 'slug' => "hixotic", 'initials' => "HI", 'value' => 6 ),
        array( 'name' => "Higher Arousal", 'slug' => "higher-arousal", 'initials' => "HA", 'value' => 6 ),
        array( 'name' => "Honey Dabber", 'slug' => "honey-dabber", 'initials' => "HD", 'value' => 6 ),
        array( 'name' => "ISPURE", 'slug' => "ispure", 'initials' => "IS", 'value' => 6 ),
        array( 'name' => "Indacloud", 'slug' => "indacloud", 'initials' => "IN", 'value' => 6 ),
        array( 'name' => "Indica Puzzles", 'slug' => "indica-puzzles", 'initials' => "IP", 'value' => 6 ),
        array( 'name' => "JOB", 'slug' => "job", 'initials' => "JO", 'value' => 6 ),
        array( 'name' => "Jelique", 'slug' => "jelique", 'initials' => "JE", 'value' => 6 ),
        array( 'name' => "Killer Acid", 'slug' => "killer-acid", 'initials' => "KA", 'value' => 6 ),
        array( 'name' => "LA Pipes", 'slug' => "la-pipes", 'initials' => "LP", 'value' => 6 ),
        array( 'name' => "MIT45", 'slug' => "mit45", 'initials' => "MI", 'value' => 6 ),
        array( 'name' => "Medusa Customs", 'slug' => "medusa-customs", 'initials' => "MC", 'value' => 6 ),
        array( 'name' => "MountainHigh", 'slug' => "mountainhigh", 'initials' => "MO", 'value' => 6 ),
        array( 'name' => "NEO", 'slug' => "neo", 'initials' => "NE", 'value' => 6 ),
        array( 'name' => "PAW:20", 'slug' => "paw-20", 'initials' => "P2", 'value' => 6 ),
        array( 'name' => "Personal Fav", 'slug' => "personal-fav", 'initials' => "PF", 'value' => 6 ),
        array( 'name' => "Piece water", 'slug' => "piece-water", 'initials' => "PW", 'value' => 6 ),
        array( 'name' => "Piranha", 'slug' => "piranha", 'initials' => "PI", 'value' => 6 ),
        array( 'name' => "Pot-Pourri", 'slug' => "pot-pourri", 'initials' => "PP", 'value' => 6 ),
        array( 'name' => "Pulsar Sipper", 'slug' => "pulsar-sipper", 'initials' => "PS", 'value' => 6 ),
        array( 'name' => "Pure Instinct", 'slug' => "pure-instinct", 'initials' => "PI", 'value' => 6 ),
        array( 'name' => "Randy's", 'slug' => "randys", 'initials' => "RS", 'value' => 6 ),
        array( 'name' => "Ritual", 'slug' => "ritual", 'initials' => "RI", 'value' => 6 ),
        array( 'name' => "Santa Cruz Shredder", 'slug' => "santa-cruz-shredder", 'initials' => "SC", 'value' => 6 ),
        array( 'name' => "Sivan", 'slug' => "sivan", 'initials' => "SI", 'value' => 6 ),
        array( 'name' => "Slightly Elevated", 'slug' => "slightly-elevated", 'initials' => "SE", 'value' => 6 ),
        array( 'name' => "Smokezilla", 'slug' => "smokezilla", 'initials' => "SM", 'value' => 6 ),
        array( 'name' => "Spyglass Wellness", 'slug' => "spyglass-wellness", 'initials' => "SW", 'value' => 6 ),
        array( 'name' => "Twizzlers", 'slug' => "twizzlers", 'initials' => "TW", 'value' => 6 ),
        array( 'name' => "URB", 'slug' => "urb", 'initials' => "UR", 'value' => 6 ),
        array( 'name' => "Vale Detox", 'slug' => "vale-detox", 'initials' => "VD", 'value' => 6 ),
        array( 'name' => "Vivant", 'slug' => "vivant", 'initials' => "VI", 'value' => 6 ),
        array( 'name' => "WNC CBD", 'slug' => "wnc-cbd", 'initials' => "WC", 'value' => 6 ),
        array( 'name' => "White Rhino", 'slug' => "white-rhino", 'initials' => "WR", 'value' => 6 ),
        array( 'name' => "Wild Hemp", 'slug' => "wild-hemp", 'initials' => "WH", 'value' => 6 ),
        array( 'name' => "Wormhole", 'slug' => "wormhole", 'initials' => "WO", 'value' => 6 ),
        array( 'name' => "XTAR", 'slug' => "xtar", 'initials' => "XT", 'value' => 6 ),
        array( 'name' => "AWS", 'slug' => "aws", 'initials' => "AW", 'value' => 5 ),
        array( 'name' => "BeWicked", 'slug' => "bewicked", 'initials' => "BE", 'value' => 5 ),
        array( 'name' => "Beautiful Burns", 'slug' => "beautiful-burns", 'initials' => "BB", 'value' => 5 ),
        array( 'name' => "Blue Scorpion", 'slug' => "blue-scorpion", 'initials' => "BS", 'value' => 5 ),
        array( 'name' => "Blunt Effects", 'slug' => "blunt-effects", 'initials' => "BE", 'value' => 5 ),
        array( 'name' => "CBD Daily", 'slug' => "cbd-daily", 'initials' => "CD", 'value' => 5 ),
        array( 'name' => "Calibear", 'slug' => "calibear", 'initials' => "CA", 'value' => 5 ),
        array( 'name' => "Crush", 'slug' => "crush", 'initials' => "CR", 'value' => 5 ),
        array( 'name' => "Dazed", 'slug' => "dazed", 'initials' => "DA", 'value' => 5 ),
        array( 'name' => "Death Row Records", 'slug' => "death-row-records", 'initials' => "DR", 'value' => 5 ),
        array( 'name' => "Doc Johnson", 'slug' => "doc-johnson", 'initials' => "DJ", 'value' => 5 ),
        array( 'name' => "Dozo", 'slug' => "dozo", 'initials' => "DO", 'value' => 5 ),
        array( 'name' => "Dr. Greenthumbs", 'slug' => "dr-greenthumbs", 'initials' => "DG", 'value' => 5 ),
        array( 'name' => "Efes1t", 'slug' => "efes1t", 'initials' => "EF", 'value' => 5 ),
        array( 'name' => "Evolved", 'slug' => "evolved", 'initials' => "EV", 'value' => 5 ),
        array( 'name' => "Exodus", 'slug' => "exodus", 'initials' => "EX", 'value' => 5 ),
        array( 'name' => "Eye of Love", 'slug' => "eye-of-love", 'initials' => "EO", 'value' => 5 ),
        array( 'name' => "Fantasy Lingerie", 'slug' => "fantasy-lingerie", 'initials' => "FL", 'value' => 5 ),
        array( 'name' => "GOO'D Gush", 'slug' => "good-gush", 'initials' => "GD", 'value' => 5 ),
        array( 'name' => "Genius Pipe", 'slug' => "genius-pipe", 'initials' => "GP", 'value' => 5 ),
        array( 'name' => "Glass House", 'slug' => "glass-house", 'initials' => "GH", 'value' => 5 ),
        array( 'name' => "Groove Glass", 'slug' => "groove-glass", 'initials' => "GG", 'value' => 5 ),
        array( 'name' => "HALF BAK'D", 'slug' => "half-bakd", 'initials' => "HB", 'value' => 5 ),
        array( 'name' => "HemPleasure", 'slug' => "hempleasure", 'initials' => "HE", 'value' => 5 ),
        array( 'name' => "High Climax", 'slug' => "high-climax", 'initials' => "HC", 'value' => 5 ),
        array( 'name' => "High Hemp", 'slug' => "high-hemp", 'initials' => "HH", 'value' => 5 ),
        array( 'name' => "Higher Celebrations", 'slug' => "higher-celebrations", 'initials' => "HC", 'value' => 5 ),
        array( 'name' => "Hot Tamales", 'slug' => "hot-tamales", 'initials' => "HT", 'value' => 5 ),
        array( 'name' => "Hulkamania", 'slug' => "hulkamania", 'initials' => "HU", 'value' => 5 ),
        array( 'name' => "Infinity", 'slug' => "infinity", 'initials' => "IN", 'value' => 5 ),
        array( 'name' => "Intimate Earth", 'slug' => "intimate-earth", 'initials' => "IE", 'value' => 5 ),
        array( 'name' => "Iroha", 'slug' => "iroha", 'initials' => "IR", 'value' => 5 ),
        array( 'name' => "JO", 'slug' => "jo", 'initials' => "JO", 'value' => 5 ),
        array( 'name' => "Kayd Mayd", 'slug' => "kayd-mayd", 'initials' => "KM", 'value' => 5 ),
        array( 'name' => "Kush RX", 'slug' => "kush-rx", 'initials' => "KR", 'value' => 5 ),
        array( 'name' => "LELO", 'slug' => "lelo", 'initials' => "LE", 'value' => 5 ),
        array( 'name' => "LITL", 'slug' => "litl", 'initials' => "LI", 'value' => 5 ),
        array( 'name' => "La Nua", 'slug' => "la-nua", 'initials' => "LN", 'value' => 5 ),
        array( 'name' => "Le Wand", 'slug' => "le-wand", 'initials' => "LW", 'value' => 5 ),
        array( 'name' => "Love Not War", 'slug' => "love-not-war", 'initials' => "LN", 'value' => 5 ),
        array( 'name' => "Lucienne", 'slug' => "lucienne", 'initials' => "LU", 'value' => 5 ),
        array( 'name' => "Mamba Grinders", 'slug' => "mamba-grinders", 'initials' => "MG", 'value' => 5 ),
        array( 'name' => "Maxx Out", 'slug' => "maxx-out", 'initials' => "MO", 'value' => 5 ),
        array( 'name' => "Mdrn Mood", 'slug' => "mdrn-mood", 'initials' => "MM", 'value' => 5 ),
        array( 'name' => "MiniNail", 'slug' => "mininail", 'initials' => "MI", 'value' => 5 ),
        array( 'name' => "Modus", 'slug' => "modus", 'initials' => "MO", 'value' => 5 ),
        array( 'name' => "Mystic Timber", 'slug' => "mystic-timber", 'initials' => "MT", 'value' => 5 ),
        array( 'name' => "New Age", 'slug' => "new-age", 'initials' => "NA", 'value' => 5 ),
        array( 'name' => "Newport Butane", 'slug' => "newport-butane", 'initials' => "NB", 'value' => 5 ),
        array( 'name' => "Nicky Davis", 'slug' => "nicky-davis", 'initials' => "ND", 'value' => 5 ),
        array( 'name' => "Odyssey Mushrooms", 'slug' => "odyssey-mushrooms", 'initials' => "OM", 'value' => 5 ),
        array( 'name' => "Orange Chronic", 'slug' => "orange-chronic", 'initials' => "OC", 'value' => 5 ),
        array( 'name' => "Otto", 'slug' => "otto", 'initials' => "OT", 'value' => 5 ),
        array( 'name' => "Packwoods", 'slug' => "packwoods", 'initials' => "PA", 'value' => 5 ),
        array( 'name' => "Pastease", 'slug' => "pastease", 'initials' => "PA", 'value' => 5 ),
        array( 'name' => "Pipedream", 'slug' => "pipedream", 'initials' => "PI", 'value' => 5 ),
        array( 'name' => "Powermatic", 'slug' => "powermatic", 'initials' => "PO", 'value' => 5 ),
        array( 'name' => "Primo Stash Gear", 'slug' => "primo-stash-gear", 'initials' => "PS", 'value' => 5 ),
        array( 'name' => "Retro Highz", 'slug' => "retro-highz", 'initials' => "RH", 'value' => 5 ),
        array( 'name' => "Ric Flair Drip", 'slug' => "ric-flair-drip", 'initials' => "RF", 'value' => 5 ),
        array( 'name' => "Rose Palms", 'slug' => "rose-palms", 'initials' => "RP", 'value' => 5 ),
        array( 'name' => "Sensuva", 'slug' => "sensuva", 'initials' => "SE", 'value' => 5 ),
        array( 'name' => "Skilletools", 'slug' => "skilletools", 'initials' => "SK", 'value' => 5 ),
        array( 'name' => "Skins Touch", 'slug' => "skins-touch", 'initials' => "ST", 'value' => 5 ),
        array( 'name' => "Sporetuality", 'slug' => "sporetuality", 'initials' => "SP", 'value' => 5 ),
        array( 'name' => "Stink Sack", 'slug' => "stink-sack", 'initials' => "SS", 'value' => 5 ),
        array( 'name' => "Stoner Vibes", 'slug' => "stoner-vibes", 'initials' => "SV", 'value' => 5 ),
        array( 'name' => "Sugar Cloud", 'slug' => "sugar-cloud", 'initials' => "SC", 'value' => 5 ),
        array( 'name' => "Swiss Navy", 'slug' => "swiss-navy", 'initials' => "SN", 'value' => 5 ),
        array( 'name' => "TENGA", 'slug' => "tenga", 'initials' => "TE", 'value' => 5 ),
        array( 'name' => "Tantus", 'slug' => "tantus", 'initials' => "TA", 'value' => 5 ),
        array( 'name' => "Thicket", 'slug' => "thicket", 'initials' => "TH", 'value' => 5 ),
        array( 'name' => "Tronian", 'slug' => "tronian", 'initials' => "TR", 'value' => 5 ),
        array( 'name' => "Twisted Hemp", 'slug' => "twisted-hemp", 'initials' => "TH", 'value' => 5 ),
        array( 'name' => "Twisty - 7Pipe", 'slug' => "twisty-7pipe", 'initials' => "T7", 'value' => 5 ),
        array( 'name' => "VeDO", 'slug' => "vedo", 'initials' => "VE", 'value' => 5 ),
        array( 'name' => "Vivid", 'slug' => "vivid", 'initials' => "VI", 'value' => 5 ),
        array( 'name' => "Wild Berry", 'slug' => "wild-berry", 'initials' => "WB", 'value' => 5 ),
        array( 'name' => "Wood Rocket", 'slug' => "wood-rocket", 'initials' => "WR", 'value' => 5 ),
        array( 'name' => "Yujean", 'slug' => "yujean", 'initials' => "YU", 'value' => 5 ),
        array( 'name' => "Zeppelin", 'slug' => "zeppelin", 'initials' => "ZE", 'value' => 5 ),
        array( 'name' => "Zion Herbals", 'slug' => "zion-herbals", 'initials' => "ZH", 'value' => 5 ),
        array( 'name' => "b-Vibe", 'slug' => "b-vibe", 'initials' => "BV", 'value' => 5 ),
        array( 'name' => "ATRx Labs", 'slug' => "atrx-labs", 'initials' => "AL", 'value' => 4 ),
        array( 'name' => "Apex Ancillary", 'slug' => "apex-ancillary", 'initials' => "AA", 'value' => 4 ),
        array( 'name' => "Appalachian Growers", 'slug' => "appalachian-growers", 'initials' => "AG", 'value' => 4 ),
        array( 'name' => "Art of Smoke", 'slug' => "art-of-smoke", 'initials' => "AO", 'value' => 4 ),
        array( 'name' => "Astral Project", 'slug' => "astral-project", 'initials' => "AP", 'value' => 4 ),
        array( 'name' => "Boost", 'slug' => "boost", 'initials' => "BO", 'value' => 4 ),
        array( 'name' => "Dreamgirl", 'slug' => "dreamgirl", 'initials' => "DR", 'value' => 4 ),
        array( 'name' => "EG Glass", 'slug' => "eg-glass", 'initials' => "EG", 'value' => 4 ),
        array( 'name' => "Endo", 'slug' => "endo", 'initials' => "EN", 'value' => 4 ),
        array( 'name' => "Fantasy Female", 'slug' => "fantasy-female", 'initials' => "FF", 'value' => 4 ),
        array( 'name' => "Fifty Shades of Grey", 'slug' => "fifty-shades-of-grey", 'initials' => "FS", 'value' => 4 ),
        array( 'name' => "Gaysentials", 'slug' => "gaysentials", 'initials' => "GA", 'value' => 4 ),
        array( 'name' => "GoodHead", 'slug' => "goodhead", 'initials' => "GO", 'value' => 4 ),
        array( 'name' => "Haze", 'slug' => "haze", 'initials' => "HA", 'value' => 4 ),
        array( 'name' => "Hershey's", 'slug' => "hersheys", 'initials' => "HS", 'value' => 4 ),
        array( 'name' => "Hit Kit", 'slug' => "hit-kit", 'initials' => "HK", 'value' => 4 ),
        array( 'name' => "Hostess Cakes", 'slug' => "hostess-cakes", 'initials' => "HC", 'value' => 4 ),
        array( 'name' => "Hush Kratom", 'slug' => "hush-kratom", 'initials' => "HK", 'value' => 4 ),
        array( 'name' => "Hydroxie", 'slug' => "hydroxie", 'initials' => "HY", 'value' => 4 ),
        array( 'name' => "Hyphoria", 'slug' => "hyphoria", 'initials' => "HY", 'value' => 4 ),
        array( 'name' => "Ice Breakers", 'slug' => "ice-breakers", 'initials' => "IB", 'value' => 4 ),
        array( 'name' => "Just CBD", 'slug' => "just-cbd", 'initials' => "JC", 'value' => 4 ),
        array( 'name' => "Let's Drink To That", 'slug' => "lets-drink-to-that", 'initials' => "LS", 'value' => 4 ),
        array( 'name' => "Lift Ticket", 'slug' => "lift-ticket", 'initials' => "LT", 'value' => 4 ),
        array( 'name' => "Little Genie", 'slug' => "little-genie", 'initials' => "LG", 'value' => 4 ),
        array( 'name' => "Lotus Cones", 'slug' => "lotus-cones", 'initials' => "LC", 'value' => 4 ),
        array( 'name' => "Maia Toys", 'slug' => "maia-toys", 'initials' => "MT", 'value' => 4 ),
        array( 'name' => "Mike and Ike", 'slug' => "mike-and-ike", 'initials' => "MA", 'value' => 4 ),
        array( 'name' => "Mitra Botanicals", 'slug' => "mitra-botanicals", 'initials' => "MB", 'value' => 4 ),
        array( 'name' => "POP Cones", 'slug' => "pop-cones", 'initials' => "PC", 'value' => 4 ),
        array( 'name' => "Peak", 'slug' => "peak", 'initials' => "PE", 'value' => 4 ),
        array( 'name' => "Phunky Phresh", 'slug' => "phunky-phresh", 'initials' => "PP", 'value' => 4 ),
        array( 'name' => "Pink Floyd", 'slug' => "pink-floyd", 'initials' => "PF", 'value' => 4 ),
        array( 'name' => "Press'd", 'slug' => "pressd", 'initials' => "PD", 'value' => 4 ),
        array( 'name' => "Reese's", 'slug' => "reeses", 'initials' => "RS", 'value' => 4 ),
        array( 'name' => "Sincerely", 'slug' => "sincerely", 'initials' => "SI", 'value' => 4 ),
        array( 'name' => "Skunk", 'slug' => "skunk", 'initials' => "SK", 'value' => 4 ),
        array( 'name' => "Smosi", 'slug' => "smosi", 'initials' => "SM", 'value' => 4 ),
        array( 'name' => "Steven Rhodes", 'slug' => "steven-rhodes", 'initials' => "SR", 'value' => 4 ),
        array( 'name' => "Taylor Gang", 'slug' => "taylor-gang", 'initials' => "TG", 'value' => 4 ),
        array( 'name' => "Terp Wipes", 'slug' => "terp-wipes", 'initials' => "TW", 'value' => 4 ),
        array( 'name' => "VIVAZEN", 'slug' => "vivazen", 'initials' => "VI", 'value' => 4 ),
        array( 'name' => "Wacky Grinderz", 'slug' => "wacky-grinderz", 'initials' => "WG", 'value' => 4 ),
        array( 'name' => "Wakit", 'slug' => "wakit", 'initials' => "WA", 'value' => 4 ),
        array( 'name' => "York Peppermint", 'slug' => "york-peppermint", 'initials' => "YP", 'value' => 4 ),
        array( 'name' => "Banana Bros", 'slug' => "banana-bros", 'initials' => "BB", 'value' => 3 ),
        array( 'name' => "Bee's Knee's CBD's", 'slug' => "bees-knees-cbds", 'initials' => "BS", 'value' => 3 ),
        array( 'name' => "Crafty", 'slug' => "crafty", 'initials' => "CR", 'value' => 3 ),
        array( 'name' => "Dan Morris", 'slug' => "dan-morris", 'initials' => "DM", 'value' => 3 ),
        array( 'name' => "Elephant Brands", 'slug' => "elephant-brands", 'initials' => "EB", 'value' => 3 ),
        array( 'name' => "GCP Glass City Pipes", 'slug' => "gcp-glass-city-pipes", 'initials' => "GG", 'value' => 3 ),
        array( 'name' => "Neva Nude", 'slug' => "neva-nude", 'initials' => "NN", 'value' => 3 ),
        array( 'name' => "Whip-it!", 'slug' => "whip-it", 'initials' => "WI", 'value' => 3 ),
        array( 'name' => "Ankomn", 'slug' => "ankomn", 'initials' => "AN", 'value' => 2 ),
        array( 'name' => "BIGFUN", 'slug' => "bigfun", 'initials' => "BI", 'value' => 2 ),
        array( 'name' => "CannaAid", 'slug' => "cannaaid", 'initials' => "CA", 'value' => 2 ),
        array( 'name' => "Cloud 8", 'slug' => "cloud-8", 'initials' => "C8", 'value' => 2 ),
        array( 'name' => "Concentrated Concepts", 'slug' => "concentrated-concepts", 'initials' => "CC", 'value' => 2 ),
        array( 'name' => "Cyclones", 'slug' => "cyclones", 'initials' => "CY", 'value' => 2 ),
        array( 'name' => "Lover's Candy", 'slug' => "lovers-candy", 'initials' => "LS", 'value' => 2 ),
        array( 'name' => "Nitecore", 'slug' => "nitecore", 'initials' => "NI", 'value' => 2 ),
        array( 'name' => "NoGoo", 'slug' => "nogoo", 'initials' => "NO", 'value' => 2 ),
        array( 'name' => "Randy's Roots", 'slug' => "randys-roots", 'initials' => "RS", 'value' => 2 ),
        array( 'name' => "Santa's Secret", 'slug' => "santas-secret", 'initials' => "SS", 'value' => 2 ),
        array( 'name' => "ShishaTech", 'slug' => "shishatech", 'initials' => "SH", 'value' => 2 ),
        array( 'name' => "Smojo", 'slug' => "smojo", 'initials' => "SM", 'value' => 2 ),
        array( 'name' => "Solopipe", 'slug' => "solopipe", 'initials' => "SO", 'value' => 2 ),
        array( 'name' => "V Syndicate", 'slug' => "v-syndicate", 'initials' => "VS", 'value' => 2 ),
        array( 'name' => "BudBud", 'slug' => "budbud", 'initials' => "BU", 'value' => 1 ),
        array( 'name' => "CannaRelief", 'slug' => "cannarelief", 'initials' => "CA", 'value' => 1 ),
        array( 'name' => "Cannabolish", 'slug' => "cannabolish", 'initials' => "CA", 'value' => 1 ),
        array( 'name' => "Earthly Body", 'slug' => "earthly-body", 'initials' => "EB", 'value' => 1 ),
        array( 'name' => "Jerome Baker Designs", 'slug' => "jerome-baker-designs", 'initials' => "JB", 'value' => 1 ),
        array( 'name' => "Julietta", 'slug' => "julietta", 'initials' => "JU", 'value' => 1 ),
        array( 'name' => "World's Biggest", 'slug' => "worlds-biggest", 'initials' => "WS", 'value' => 1 ),
        array( 'name' => "Zico", 'slug' => "zico", 'initials' => "ZI", 'value' => 1 ),
    );
}

/* Recently joined brands (no Value -> rank 7) */
function sdn_new_brands() {
    return array(
        array( 'name' => "Ancient Creations", 'slug' => "ancient-creations", 'initials' => "AC", 'value' => 7 ),
        array( 'name' => "Black Market Pet Supply", 'slug' => "black-market-pet-supply", 'initials' => "BM", 'value' => 7 ),
        array( 'name' => "Cipher", 'slug' => "cipher", 'initials' => "CI", 'value' => 7 ),
        array( 'name' => "Edie Parker", 'slug' => "edie-parker", 'initials' => "EP", 'value' => 7 ),
        array( 'name' => "Grassroots", 'slug' => "grassroots", 'initials' => "GR", 'value' => 7 ),
        array( 'name' => "High Knife", 'slug' => "high-knife", 'initials' => "HK", 'value' => 7 ),
        array( 'name' => "Hippy Chews", 'slug' => "hippy-chews", 'initials' => "HC", 'value' => 7 ),
        array( 'name' => "Hy Bird", 'slug' => "hy-bird", 'initials' => "HB", 'value' => 7 ),
        array( 'name' => "JM Enterprises", 'slug' => "jm-enterprises", 'initials' => "JE", 'value' => 7 ),
        array( 'name' => "ORL", 'slug' => "orl", 'initials' => "OR", 'value' => 7 ),
        array( 'name' => "Smoxy", 'slug' => "smoxy", 'initials' => "SM", 'value' => 7 ),
        array( 'name' => "Tubr", 'slug' => "tubr", 'initials' => "TU", 'value' => 7 ),
        array( 'name' => "Ultra93 Hemp Co.", 'slug' => "ultra93-hemp-co", 'initials' => "UH", 'value' => 7 ),
        array( 'name' => "WeighMax", 'slug' => "weighmax", 'initials' => "WE", 'value' => 7 ),
    );
}
